### ISSUE TITLE
Set deletion_protection=false in order to destroy resource "google_bigquery_table"

### ISSUE THREAD

**Issue by BadCopingMechanisms** [BrunoReboul/terraform-google-realtime-asset-monitor#85]
Hi Bruno,

In your file modules/stream2bq/main.tf, for the resources  "google_bigquery_table" "assets" "compliance_status" and "violations" you're setting the deletion_protection parameter to true. 

In order to be able to destroy those resources through terraform, it needs to be set to false. 

I understand that the documentation recommend to not set this field (or set it to true) until you're ready to destroy, but would it be possible to change the value to false ? I tried to override the value when deploying RAM but without success. 

Best regards,

**Comment by BrunoReboul** [comment]
Hi Yann,

Thanks for contributing.

Instead of changing the `deletion_protection` setting from `true` to `false` it is now exposed from the module `realtime-asset-monitor` as variable `bq_tables_deletion_protection` with a default value to `true` that you can change to `false`

to be released in v0.7.1
